repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.12.2
    hooks:
      - id: golangci-lint-config-verify
      - id: golangci-lint

  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        entry: bash -c 'go fmt ./...'
        language: system
        pass_filenames: false
        types: [go]

      - id: go-vet
        name: go vet
        entry: bash -c 'go vet ./...'
        language: system
        pass_filenames: false
        types: [go]

      - id: go-test
        name: go test
        entry: bash -c 'go test ./...'
        language: system
        pass_filenames: false
        types: [go]
